[project]
name = "resumay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.6",
    "sh>=2.2.2",
    "typer>=0.16.0",
    "typing>=3.10.0.0",
    "weasyprint>=65.1",
]
